Resources:
  IssueTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: Context
          AttributeType: S
        - AttributeName: AccountUUID
          AttributeType: S
        - AttributeName: IssueID
          AttributeType: S
      KeySchema:
        - AttributeName: Context
          KeyType: HASH
        - AttributeName: IssueID
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: AccountUUID
              KeyType: HASH
          Projection:
            ProjectionType: "KEYS_ONLY"
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
